openapi: 3.0.0
info:
  title: Loan Origination System API
  version: 1.0.0
  description: API for submitting loan applications and uploading documents for Small and Medium Businesses (SMBs)

servers:
  - url: http://localhost:4566/restapis/bysdf8fgq1/local/_user_request_

paths:
  /applications:
    post:
      summary: Submit a new loan application
      operationId: submitApplication
      tags:
        - Applications
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoanApplicationRequest"
      responses:
        "201":
          description: Application submitted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationResponse"
        "400":
          description: Bad request
        "500":
          description: Internal server error

  /documents:
    post:
      summary: Upload a document for a loan application
      operationId: uploadDocument
      tags:
        - Documents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DocumentUploadRequest"
      responses:
        "201":
          description: Document uploaded successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentResponse"
        "400":
          description: Bad request
        "500":
          description: Internal server error

  /loan-products:
    post:
      summary: Create a new loan product
      operationId: createLoanProduct
      tags:
        - Loan Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoanProductRequest"
      responses:
        "201":
          description: Loan product created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoanProductResponse"
        "400":
          description: Bad request
        "500":
          description: Internal server error

    get:
      summary: List all loan products
      operationId: listLoanProducts
      tags:
        - Loan Products
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/LoanProductResponse"
        "500":
          description: Internal server error

  /loan-products/{productId}:
    get:
      summary: Retrieve a specific loan product
      operationId: getLoanProduct
      tags:
        - Loan Products
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoanProductResponse"
        "404":
          description: Loan product not found
        "500":
          description: Internal server error

    put:
      summary: Update a loan product
      operationId: updateLoanProduct
      tags:
        - Loan Products
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoanProductRequest"
      responses:
        "200":
          description: Loan product updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoanProductResponse"
        "400":
          description: Bad request
        "404":
          description: Loan product not found
        "500":
          description: Internal server error

    delete:
      summary: Deprecate a loan product (soft delete)
      operationId: deprecateLoanProduct
      tags:
        - Loan Products
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Loan product deprecated successfully
        "404":
          description: Loan product not found
        "500":
          description: Internal server error

  /loan-products/{productId}/versions:
    post:
      summary: Create a new version of a loan product
      operationId: createLoanProductVersion
      tags:
        - Loan Products
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoanProductRequest"
      responses:
        "201":
          description: New version created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoanProductResponse"
        "400":
          description: Bad request
        "404":
          description: Loan product not found
        "500":
          description: Internal server error

    get:
      summary: List all versions of a loan product
      operationId: listLoanProductVersions
      tags:
        - Loan Products
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/LoanProductResponse"
        "404":
          description: Loan product not found
        "500":
          description: Internal server error

  /loan-products/{productId}/versions/{versionNumber}:
    get:
      summary: Get a specific version of a loan product
      operationId: getLoanProductVersion
      tags:
        - Loan Products
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
        - name: versionNumber
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoanProductResponse"
        "404":
          description: Loan product or version not found
        "500":
          description: Internal server error

  /loan-products/search:
    get:
      summary: Search loan products based on criteria
      operationId: searchLoanProducts
      tags:
        - Loan Products
      parameters:
        - name: productType
          in: query
          schema:
            type: string
        - name: minAmount
          in: query
          schema:
            type: number
        - name: maxAmount
          in: query
          schema:
            type: number
        - name: interestRateType
          in: query
          schema:
            type: string
            enum: [Fixed, Variable]
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/LoanProductResponse"
        "500":
          description: Internal server error

components:
  schemas:
    LoanApplicationRequest:
      type: object
      required:
        - business
        - requestedAmount
        - loanPurpose
        - loanTerm
      properties:
        business:
          $ref: "#/components/schemas/Business"
        requestedAmount:
          type: number
          format: float
        loanPurpose:
          type: string
        loanTerm:
          type: integer
          description: Loan term in months
        collateralType:
          type: string
        collateralValue:
          type: number
          format: float

    Business:
      type: object
      required:
        - legalName
        - businessStructure
        - taxId
        - dateEstablished
        - numberOfEmployees
        - annualRevenue
        - industryCode
        - address
        - contactInformation
        - financialStatements
      properties:
        legalName:
          type: string
        tradingName:
          type: string
        businessStructure:
          type: string
          enum: [SOLE_PROPRIETORSHIP, PARTNERSHIP, LLC, CORPORATION]
        taxId:
          type: string
        dateEstablished:
          type: string
          format: date
        numberOfEmployees:
          type: integer
        annualRevenue:
          type: number
          format: float
        industryCode:
          type: string
        address:
          $ref: "#/components/schemas/Address"
        contactInformation:
          $ref: "#/components/schemas/ContactInformation"
        financialStatements:
          $ref: "#/components/schemas/FinancialStatements"
        creditHistory:
          $ref: "#/components/schemas/CreditHistory"

    Address:
      type: object
      properties:
        street:
          type: string
        city:
          type: string
        state:
          type: string
        postalCode:
          type: string
        country:
          type: string

    ContactInformation:
      type: object
      properties:
        primaryContactName:
          type: string
        phoneNumber:
          type: string
        email:
          type: string

    FinancialStatements:
      type: object
      properties:
        balanceSheet:
          $ref: "#/components/schemas/BalanceSheet"
        incomeStatement:
          $ref: "#/components/schemas/IncomeStatement"
        cashFlowStatement:
          $ref: "#/components/schemas/CashFlowStatement"

    BalanceSheet:
      type: object
      properties:
        totalAssets:
          type: number
          format: float
        totalLiabilities:
          type: number
          format: float
        ownersEquity:
          type: number
          format: float
        currentAssets:
          type: number
          format: float
        currentLiabilities:
          type: number
          format: float

    IncomeStatement:
      type: object
      properties:
        revenue:
          type: number
          format: float
        expenses:
          type: number
          format: float
        netIncome:
          type: number
          format: float

    CashFlowStatement:
      type: object
      properties:
        operatingCashFlow:
          type: number
          format: float
        investingCashFlow:
          type: number
          format: float
        financingCashFlow:
          type: number
          format: float

    CreditHistory:
      type: object
      properties:
        bankruptcies:
          type: integer
        liens:
          type: integer
        judgments:
          type: integer
        defaultedLoans:
          type: integer

    ApplicationResponse:
      type: object
      properties:
        applicationId:
          type: string
        businessId:
          type: string

    DocumentUploadRequest:
      type: object
      required:
        - applicationId
        - documentType
        - fileContent
      properties:
        applicationId:
          type: string
        documentType:
          type: string
        fileContent:
          type: string
          format: byte
          description: Base64 encoded file content

    DocumentResponse:
      type: object
      properties:
        documentId:
          type: string
        key:
          type: string

    LoanProductRequest:
      type: object
      required:
        - productName
        - productType
        - minLoanAmount
        - maxLoanAmount
        - interestRateType
        - baseInterestRate
        - termOptions
      properties:
        productName:
          type: string
        productType:
          type: string
        minLoanAmount:
          type: number
        maxLoanAmount:
          type: number
        interestRateType:
          type: string
          enum: [Fixed, Variable]
        baseInterestRate:
          type: number
        termOptions:
          type: array
          items:
            type: integer
        eligibilityCriteria:
          type: object
        fees:
          type: object
        collateralRequirements:
          type: string
        underwritingGuidelines:
          type: string

    LoanProductResponse:
      type: object
      properties:
        productId:
          type: string
        versionNumber:
          type: integer
        productName:
          type: string
        productType:
          type: string
        minLoanAmount:
          type: number
        maxLoanAmount:
          type: number
        interestRateType:
          type: string
          enum: [Fixed, Variable]
        baseInterestRate:
          type: number
        termOptions:
          type: array
          items:
            type: integer
        eligibilityCriteria:
          type: object
        fees:
          type: object
        collateralRequirements:
          type: string
        underwritingGuidelines:
          type: string
        status:
          type: string
          enum: [Active, Inactive, Deprecated]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
