service: loan-origination-system

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    STAGE: ${self:provider.stage}
  deploymentMethod: direct
  logs:
    lambda: true

custom:
  localstack:
    stages:
      - dev
    host: http://localhost
    edgePort: 4566
    autostart: false
    lambda:
      mountCode: true
  documentsBucketName: los-documents-${self:provider.stage}

plugins:
  - serverless-step-functions
  - serverless-offline
  - serverless-localstack

functions:
  applicationSubmission:
    handler: dist/handlers/applicationSubmission.handler
    events:
      - http:
          path: applications
          method: post

  documentUpload:
    handler: dist/handlers/documentUpload.handler
    timeout: 15
    environment:
      DOCUMENTS_BUCKET: ${self:custom.documentsBucketName}
      LOAN_APPLICATION_WORKFLOW_ARN:
        Ref: LoanApplicationWorkflow
    events:
      - http:
          path: documents
          method: post

  creditCheck:
    handler: dist/handlers/creditCheck.handler

  underwritingEngine:
    handler: dist/handlers/underwritingEngine.handler

  notificationSystem:
    handler: dist/handlers/notificationSystem.handler
    timeout: 120
    environment:
      NOTIFICATION_TOPIC_ARN:
        Ref: NotificationTopic

stepFunctions:
  stateMachines:
    loanApplicationWorkflow:
      id: LoanApplicationWorkflow
      definition: ${file(stepFunctions/loanApplicationWorkflow.json)}

resources:
  Resources:
    LoanApplicationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: LoanApplications
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

    BusinessesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Businesses
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

    UnderwritingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Underwriting
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

    DocumentsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.documentsBucketName}

    NotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: loan-notifications-${self:provider.stage}
